package Scripting.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Scripting_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("7435e841-b1dd-44f6-80a4-37de42442fc7(Scripting)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
