package Scripting.sandbox.sandbox;

/*Generated by MPS */


public class EmptyScript {
  public EmptyScript() {
  }

  public Object run() {
    return null;
  }

  public static void main(String[] args) {
    Object result = new EmptyScript().run();
    if (result != null) {
      System.out.println("Result: " + result);
    }
  }
}
