package Scripting.sandbox.sandbox;

/*Generated by MPS */


public class ExternalClass {
  public ExternalClass() {
  }

  public void calculate(int value) {
    System.out.println("Calculate called" + value);
  }

  public class Fooo {
    public Fooo() {
    }
  }
}
