package Scripting.sandbox.sandbox;

/*Generated by MPS */

import java.util.Arrays;

public class MyScript {
  private static int myStaticField = 10;

  private int myField = 20 + myStaticField;

  public MyScript() {
  }

  public Object run() {
    System.out.println("Foo");
    System.out.println("Bar");
    for (int i : Arrays.asList(1, 2, 3, 4, 5)) {
      System.out.println("" + i);

    }
    int localValue = 10 + calculate(30, 10) + myField + myStaticField;
    System.out.println("Baz");
    return 100 + foo("foo") + localValue + calculate(10, 20);
  }

  public int calculate(int a, int b) {
    return a + b;
  }

  public static void main(String[] args) {
    Object result = new MyScript().run();
    if (result != null) {
      System.out.println("Result: " + result);
    }
  }

  public static int foo(String value) {
    return value.length() + myStaticField;
  }
}
