package Scripting.sandbox.sandbox;

/*Generated by MPS */


public class VoidReturningScript {
  public VoidReturningScript() {
  }

  public Object run() {
    System.out.println("Running");
    return null;
  }

  public static void main(String[] args) {
    Object result = new VoidReturningScript().run();
    if (result != null) {
      System.out.println("Result: " + result);
    }
  }
}
