package Scripting.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import Scripting.behavior.Script_Behavior;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_7867971007362044082(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static SNode sourceNodeQuery_6240804956234802740(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_6240804956234802708(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_6240804956234801505(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_6240804956234741710(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_6240804956234702029(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "declaration", true);
  }

  public static SNode sourceNodeQuery_6240804956234799539(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "declaration", true);
  }

  public static SNode sourceNodeQuery_6240804956234802438(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "declaration", true);
  }

  public static SNode sourceNodeQuery_6240804956234802500(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "declaration", true);
  }

  public static Iterable sourceNodesQuery_6240804956234802728(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Script_Behavior.call_retrieveFieldDeclarations_6240804956234802648(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6240804956234802695(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Script_Behavior.call_retrieveStaticFieldDeclarations_6240804956234802612(_context.getNode());
  }

  public static Iterable sourceNodesQuery_7867971007362209467(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Script_Behavior.call_retrieveStatements_6240804956234738996(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6240804956234801490(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Script_Behavior.call_retrieveInstanceMethodDeclarations_6240804956234799549(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6240804956234706778(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Script_Behavior.call_retrieveStaticMethodDeclarations_6240804956234706787(_context.getNode());
  }
}
