package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class FieldDeclarationInScript_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public FieldDeclarationInScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.FieldDeclarationInScript";
  }
}
