package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class InstanceMethodDeclarationInScript_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public InstanceMethodDeclarationInScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.InstanceMethodDeclarationInScript";
  }
}
