package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Classifier_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.ScopeProvider_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.scope.Scope;

public class Script_BehaviorDescriptor extends Classifier_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor, ScopeProvider_BehaviorDescriptor {
  public Script_BehaviorDescriptor() {
  }

  public boolean virtual_isDescendant_7165541881557222913(SNode thisNode, SNode nodeToCompare) {
    return Script_Behavior.virtual_isDescendant_7165541881557222913(thisNode, nodeToCompare);
  }

  public Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    return Script_Behavior.virtual_getScope_3734116213129936182(thisNode, kind, child);
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.Script";
  }
}
