package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.FieldDeclaration_BehaviorDescriptor;

public class ScriptingFieldDeclaration_BehaviorDescriptor extends FieldDeclaration_BehaviorDescriptor {
  public ScriptingFieldDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.ScriptingFieldDeclaration";
  }
}
