package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.StaticFieldDeclaration_BehaviorDescriptor;

public class ScriptingStaticFieldDeclaration_BehaviorDescriptor extends StaticFieldDeclaration_BehaviorDescriptor {
  public ScriptingStaticFieldDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.ScriptingStaticFieldDeclaration";
  }
}
