package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;

public class ScriptingFieldDeclaration_Behavior {
  public static void init(SNode thisNode) {
    SNodeFactoryOperations.setNewChild(thisNode, "visibility", "jetbrains.mps.baseLanguage.structure.PrivateVisibility");
  }
}
