package Scripting.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class StaticMethodDeclarationInScript_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public StaticMethodDeclarationInScript_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Scripting.structure.StaticMethodDeclarationInScript";
  }
}
